import { i18n } from "@/i18n-config";
import "../globals.css";
import { Nunito } from "next/font/google";
import localFont from "next/font/local";
import React from "react";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import LangSwitch from "@/components/LangSwitch";

const nunito = Nunito({
  subsets: ["latin"],
});

const dana = localFont({
  src: "../../fonts/DanaVF.ttf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description:
    "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({
    lang: locale,
  }));
}

const setDir = (lang: string) => {
  switch (lang) {
    case "fa":
      return "rtl";
    case "en":
      return "ltr";
    default:
      return "";
  }
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html
      lang={params.lang}
      dir={setDir(params.lang)}
    >
      <body
        className={
          params.lang === "en"
            ? nunito.className
            : dana.className
        }
      >
        <Header />
        {children}
        <LangSwitch />
        <Footer />
      </body>
    </html>
  );
}
